name: practicesoftwaretestingDevOps

on:
  push:
    branches: [ main,dev ]
  pull_request:
    branches: [ main,dev ]
  merge_group:
    branches: [main,dev]  

jobs:
  build:
    name: Build Maven Project
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build JAR
        run: mvn clean test
        

      
