name: practicesoftwaretestingDevOps

on: 
  push:
    branches: [main,ft/pipeline]
  pull_request: 
   branches: [main,ft/pipeline]
  merge_group:
    branches: [main,ft/pipeline]

jobs:
  build:
   name: build maven project
   runs-on: windows-latest

   steps:
     - name: checkout codes
       uses: actions/checkout@v4

     - name: setup JDK
       uses: actions/setup-java@v4       
       with:
        distribution: temurin
        java-version: 17

     - name: build and test
       run: mvn clean test
     
              
